// samples/react-plugin/src/App.tsx
import { getToolViewApi, toolview } from '@i2analyze/notebook-sdk';
import { useEffect, useState } from 'react';

import ToolView from './ToolView';
import { ToolViewApiContext } from './useToolViewApi';

export default function App() {
  const [toolViewApi, setToolViewApi] = useState<
    toolview.IToolViewApi | undefined
  >();

  useEffect(() => {
    getToolViewApi().then((api) => {
      setToolViewApi(api);
    });
  }, []);

  if (toolViewApi) {
    return (
      <ToolViewApiContext.Provider value={toolViewApi}>
        <ToolView />
      </ToolViewApiContext.Provider>
    );
  } else {
    return null;
  }
}

// samples/vue-plugin/src/App.vue
<template>
  <div v-if="toolViewApi">
    <ToolView :toolViewApi="toolViewApi" />
  </div>
</template>

<script lang="ts">
import { getToolViewApi, toolview } from "@i2analyze/notebook-sdk";
import { defineComponent } from "vue";

import ToolView from "./components/ToolView.vue";

export default defineComponent({
  name: "App",
  components: {
    ToolView,
  },
  data() {
    return {
      toolViewApi: undefined as toolview.IToolViewApi | undefined,
    };
  },
  async mounted() {
    this.toolViewApi = await getToolViewApi();
  },
});
</script>

<style></style>
